name: dinar_store
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.10+10

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  permission_handler: ^11.1.0
  shared_preferences: ^2.3.2
  connectivity_plus: ^5.0.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.6
  flutter_spinkit: ^5.2.0
  dartz: ^0.10.1
  flutter_secure_storage: ^9.0.0
  flutter_bloc: ^8.1.3
  intl_phone_field: ^3.2.0
  flutter_verification_code: ^1.1.7
  awesome_bottom_bar: ^1.2.4
  geolocator: ^10.1.0
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  flutter_image_slideshow: ^0.1.6
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  vertical_tabs_flutter: ^1.0.0
  dotted_border: ^2.1.0
  url_launcher: ^6.2.4
  google_maps_flutter: ^2.5.3
  geocoding: ^2.1.1
  device_preview: ^1.2.0
  google_places_flutter: ^2.0.8
  map_location_picker: ^1.2.8+3
  flutter_keyboard_visibility: ^5.4.1
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.1.1
  easy_stepper: ^0.8.5
  cloud_firestore: ^5.0.1
  open_file: ^3.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  image_path: "assets/images/dinar_logo.png"
  android: true
  ios: true
  adaptive_icon_background: "#00784a"


flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  # example:
  fonts:
    - family: SegoeUI
      fonts:
        - asset: assets/fonts/SegoeUI.ttf

