// Plugin versions are declared in settings.gradle (pluginManagement / plugins block).
// Keeping them in one place avoids AGP/Kotlin ending up on the classpath twice.
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}


tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
